/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as exampleSum3Sol from "./ExampleSum3.sol";
export { ExampleStatelessSum3__factory } from "./ExampleStatelessSum3__factory";
