/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ErrorISum3,
  ErrorISum3Interface,
} from "../../ErrorExampleSum3.sol/ErrorISum3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "c",
        type: "uint256",
      },
    ],
    name: "calcSum3",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ErrorISum3__factory {
  static readonly abi = _abi;
  static createInterface(): ErrorISum3Interface {
    return new Interface(_abi) as ErrorISum3Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): ErrorISum3 {
    return new Contract(address, _abi, runner) as unknown as ErrorISum3;
  }
}
