/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ErrorExampleSum3__factory } from "./ErrorExampleSum3__factory";
export { ErrorISum3__factory } from "./ErrorISum3__factory";
