/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ISum3, ISum3Interface } from "../../ErrorExampleSum3.sol/ISum3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "c",
        type: "uint256",
      },
    ],
    name: "calcSum3",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISum3__factory {
  static readonly abi = _abi;
  static createInterface(): ISum3Interface {
    return new Interface(_abi) as ISum3Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISum3 {
    return new Contract(address, _abi, runner) as unknown as ISum3;
  }
}
