/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ExampleSum3,
  ExampleSum3Interface,
} from "../../ExampleSum3.sol/ExampleSum3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "c",
        type: "uint256",
      },
    ],
    name: "calcSum3",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getSum3",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102f3806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80638e2a5b251461003b578063a104464e14610057575b600080fd5b610055600480360381019061005091906101c7565b610075565b005b61005f6100fd565b60405161006c9190610229565b60405180910390f35b73030000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff16638e2a5b258484846040518463ffffffff1660e01b81526004016100c693929190610244565b600060405180830381600087803b1580156100e057600080fd5b505af11580156100f4573d6000803e3d6000fd5b50505050505050565b60008073030000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff1663a104464e6040518163ffffffff1660e01b8152600401602060405180830381865afa15801561015f573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101839190610290565b90508091505090565b600080fd5b6000819050919050565b6101a481610191565b81146101af57600080fd5b50565b6000813590506101c18161019b565b92915050565b6000806000606084860312156101e0576101df61018c565b5b60006101ee868287016101b2565b93505060206101ff868287016101b2565b9250506040610210868287016101b2565b9150509250925092565b61022381610191565b82525050565b600060208201905061023e600083018461021a565b92915050565b6000606082019050610259600083018661021a565b610266602083018561021a565b610273604083018461021a565b949350505050565b60008151905061028a8161019b565b92915050565b6000602082840312156102a6576102a561018c565b5b60006102b48482850161027b565b9150509291505056fea2646970667358221220809168385427697f8571a2fa81d6ffd9fcb93182e02b234996ae8c93bb63b97664736f6c63430008130033";

type ExampleSum3ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExampleSum3ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExampleSum3__factory extends ContractFactory {
  constructor(...args: ExampleSum3ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ExampleSum3 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ExampleSum3__factory {
    return super.connect(runner) as ExampleSum3__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExampleSum3Interface {
    return new Interface(_abi) as ExampleSum3Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): ExampleSum3 {
    return new Contract(address, _abi, runner) as unknown as ExampleSum3;
  }
}
