/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ExampleSum3__factory } from "./ExampleSum3__factory";
export { ISum3__factory } from "./ISum3__factory";
